from datetime import date, datetime, timedelta

from app.config import Settings
from app.domain import CORE_TIMEFRAMES, SUPPORTED_TIMEFRAMES
from app.models import (
    Indicator,
    KLine,
    MarketState,
    Position,
    StockTrend,
    StructureEvent,
    TradeSignal,
    TradingState,
    WatchlistItem,
)
from app.services.workbench import (
    debug_payload,
    events_payload,
    frames_payload,
    signals_payload,
    state_payload,
    workbench_watchlist,
)


def seed_workbench(session, include_5m: bool = False) -> None:
    base = datetime(2026, 6, 10, 14, 30)
    session.add(WatchlistItem(symbol="AAPL", name="Apple", active=True))
    session.add(MarketState(as_of=date(2026, 6, 10), state="RISK_ON", reason="market passed"))
    session.add(StockTrend(symbol="AAPL", as_of=date(2026, 6, 10), trend="UPTREND", reason="trend passed"))
    session.add(TradingState(symbol="AAPL", state="WAIT_15M_TRIGGER", next_wait="waiting for 15m trigger after structure"))
    for timeframe in SUPPORTED_TIMEFRAMES if include_5m else CORE_TIMEFRAMES:
        for offset in range(4):
            ts = base + timedelta(minutes=offset * 15)
            session.add(
                KLine(
                    symbol="AAPL",
                    timeframe=timeframe,
                    ts=ts,
                    open=100 + offset,
                    high=102 + offset,
                    low=99 + offset,
                    close=101 + offset,
                    volume=1000 + offset,
                )
            )
            session.add(
                Indicator(
                    symbol="AAPL",
                    timeframe=timeframe,
                    ts=ts,
                    ma20=100 + offset,
                    ma60=98 + offset,
                    macd_dif=0.5,
                    macd_dea=0.3,
                    macd_hist=0.2,
                    atr=2,
                    volume_ma20=900,
                )
            )
    structure = StructureEvent(
        symbol="AAPL",
        timeframe="60m",
        event_type="BOTTOM_STRUCTURE",
        event_ts=base + timedelta(minutes=15),
        price=101,
        pivot_low=98,
        reason="bottom passivation confirmed by key high breakout, MA20 recovery, MACD improvement, and acceptable volume",
    )
    session.add(structure)
    session.flush()
    session.add(
        TradeSignal(
            symbol="AAPL",
            signal_type="ENTRY",
            script="SCRIPT_A_BOTTOM_TREND_RESUME",
            status="PENDING",
            action="入场候选",
            entry_price=103,
            stop_price=97,
            shares=100,
            risk_amount=600,
            source_structure_id=structure.id,
            trigger_timeframe="15m",
            trigger_ts=base + timedelta(minutes=45),
            trigger_level=102,
            reason="generated by state machine, not score",
        )
    )
    session.add(
        Position(
            symbol="AAPL",
            status="OPEN",
            entry_signal_id=1,
            entry_price=103,
            stop_price=97,
            trailing_stop=101,
            shares=100,
            risk_amount=600,
            current_r=1.2,
        )
    )
    session.commit()


def test_frames_include_all_supported_timeframes_and_optional_5m_does_not_block(session):
    seed_workbench(session)

    payload = frames_payload(session, "AAPL")

    assert tuple(payload["frames"]) == SUPPORTED_TIMEFRAMES
    assert payload["frames"]["1d"]["available"] is True
    assert payload["frames"]["60m"]["events"][0]["kind"] == "BOTTOM_STRUCTURE"
    assert payload["frames"]["15m"]["signals"][0]["kind"] == "BUY"
    assert payload["frames"]["5m"]["available"] is False
    assert payload["frames"]["5m"]["bars"] == []


def test_workbench_read_models_explain_state_risk_and_debug(session):
    seed_workbench(session)
    settings = Settings(database_url="sqlite:///:memory:")

    state = state_payload(session, settings, "AAPL")
    events = events_payload(session, "AAPL")
    signals = signals_payload(session, "AAPL")
    debug = debug_payload(session, settings, "AAPL")
    rows = workbench_watchlist(session)

    assert state["trading_state"]["label"] == "等待 15 分钟触发"
    assert state["data"]["ok"] is True
    assert state["position"]["stop_price"] == 97
    assert state["playbooks"][0]["conditions"]
    assert events["events"][0]["label"] == "底结构"
    assert signals["signals"][0]["script_label"].startswith("剧本 A")
    assert debug["source"] == "server_read_model"
    assert debug["frame_summary"]["5m"]["available"] is False
    assert rows[0]["state"] == "WAIT_15M_TRIGGER"


def test_chart_markers_are_server_owned_and_have_no_score_trigger(session):
    seed_workbench(session, include_5m=True)

    payload = frames_payload(session, "AAPL")
    marker = payload["frames"]["15m"]["signals"][0]

    assert marker == {
        "ts": "2026-06-10T15:15:00",
        "price": 103,
        "kind": "BUY",
        "label": "买入",
        "status": "PENDING",
        "source_type": "ENTRY",
    }
    assert "score" not in marker
