from app.presentation import describe_market_reason, format_money, format_percent, format_reason, format_shares, label_for


def test_known_labels_are_translated_to_chinese():
    assert label_for("RISK_ON") == "风险偏好，可开新仓"
    assert label_for("ENTRY_CANDIDATE") == "入场候选"
    assert label_for("BOTTOM_STRUCTURE") == "底结构"
    assert label_for("SCRIPT_A_BOTTOM_TREND_RESUME") == "剧本 A：底结构后的趋势恢复"
    assert label_for("60m") == "60 分钟"


def test_unknown_label_falls_back_safely():
    assert label_for("NEW_INTERNAL_TAG") == "NEW_INTERNAL_TAG"
    assert label_for(None) == "-"


def test_reason_formatter_translates_common_backend_phrases():
    text = "price recovered MA20, broke recent key high, MACD improved, volume acceptable, 60m not weak; stop=123.45; shares=100; generated by state machine, not score"
    rendered = format_reason(text)
    assert "价格收复 MA20" in rendered
    assert "止损=123.45" in rendered
    assert "建议股数=100" in rendered
    assert "评分未参与触发" in rendered


def test_number_formatters_are_human_readable():
    assert format_money(1234.5) == "$1,234.50"
    assert format_percent(0.1234) == "12.3%"
    assert format_shares(1200) == "1,200 股"


def test_market_data_failure_is_not_described_as_confirmed_market_weakness():
    description = describe_market_reason("RISK_OFF", "SPY market data or indicators missing")
    assert "数据或指标不完整" in description
    assert "不代表市场已经确认转弱" in description
