from app.presentation import describe_market_reason, format_money, format_percent, format_reason, format_shares, label_for


def test_known_labels_are_translated_to_chinese():
    assert label_for("RISK_ON") == "风险偏好，可开新仓"
    assert label_for("ENTRY_CANDIDATE") == "入场候选"
    assert label_for("WAIT_15M_TRIGGER") == "等待 15 分钟触发"
    assert label_for("BOTTOM_STRUCTURE") == "底结构"
    assert label_for("SCRIPT_A_BOTTOM_TREND_RESUME") == "剧本 A：底结构后的趋势恢复"
    assert label_for("60m") == "60 分钟"
    assert label_for("CANCELLED_BY_TRIGGER") == "因触发失败取消"


def test_unknown_label_falls_back_safely():
    assert label_for("NEW_INTERNAL_TAG") == "NEW_INTERNAL_TAG"
    assert label_for(None) == "-"


def test_reason_formatter_translates_common_backend_phrases():
    text = "price recovered MA20, broke recent key high, MACD improved, volume acceptable, 60m not weak; stop=123.45; shares=100; generated by state machine, not score"
    rendered = format_reason(text)
    assert "价格收复 MA20" in rendered
    assert "止损=123.45" in rendered
    assert "建议股数=100" in rendered
    assert "评分未参与触发" in rendered


def test_reason_formatter_translates_structure_and_trigger_sources():
    rendered = format_reason(
        "structure_id=12; structure_timeframe=60m; structure_ts=2026-06-08T10:00:00; "
        "trigger_timeframe=15m; trigger_ts=2026-06-08T11:15:00; trigger_price=102.50; trigger_level=101.80"
    )
    assert "结构编号=12" in rendered
    assert "结构周期=60 分钟" in rendered
    assert "触发周期=15 分钟" in rendered
    assert "触发价=102.50" in rendered


def test_reason_formatter_translates_structure_stop_and_risk_details():
    rendered = format_reason(
        "stop_source=60m bottom structure pivot 96.00 minus 0.5 ATR (2.00); "
        "risk_per_share=7.50; allowed_loss=1000.00; position_value=13632.50"
    )
    assert "止损来源=60 分钟底结构低点 96.00" in rendered
    assert "每股风险=7.50" in rendered
    assert "允许亏损=1000.00" in rendered
    assert "建议市值=13632.50" in rendered


def test_number_formatters_are_human_readable():
    assert format_money(1234.5) == "$1,234.50"
    assert format_percent(0.1234) == "12.3%"
    assert format_shares(1200) == "1,200 股"


def test_market_data_failure_is_not_described_as_confirmed_market_weakness():
    description = describe_market_reason("RISK_OFF", "SPY market data or indicators missing")
    assert "数据或指标不完整" in description
    assert "不代表市场已经确认转弱" in description
