from __future__ import annotations

import re
from datetime import date, datetime
from typing import Any


LABELS: dict[str, str] = {
    "RISK_ON": "风险偏好，可开新仓",
    "NEUTRAL_POSITIVE": "中性偏强，谨慎开仓",
    "NEUTRAL_NEGATIVE": "中性偏弱，只管理持仓",
    "RISK_OFF": "风险关闭，禁止新仓",
    "STRONG_UPTREND": "强上涨趋势",
    "UPTREND": "上涨趋势",
    "SIDEWAYS": "震荡观察",
    "DOWNTREND": "下跌趋势",
    "UNKNOWN": "数据不足",
    "IDLE": "空闲观察",
    "TREND_OK": "趋势合格",
    "WATCH_BOTTOM": "底部观察",
    "BOTTOM_CONFIRMED": "底结构确认",
    "WAIT_ENTRY_TRIGGER": "等待入场触发",
    "ENTRY_CANDIDATE": "入场候选",
    "IN_POSITION": "持仓管理",
    "RISK_PROTECTION": "风险保护中",
    "EXIT_CANDIDATE": "退出候选",
    "COOLDOWN": "冷却期",
    "BOTTOM_PASSIVATION": "底钝化",
    "BOTTOM_STRUCTURE": "底结构",
    "BOTTOM_FAILED": "底结构失败",
    "TOP_PASSIVATION": "顶钝化",
    "TOP_STRUCTURE": "顶结构",
    "TOP_INVALIDATED": "顶结构失效",
    "SCRIPT_A_BOTTOM_TREND_RESUME": "剧本 A：底结构后的趋势恢复",
    "SCRIPT_B_TOP_INVALIDATION_CONTINUATION": "剧本 B：顶结构失效后的强趋势再上",
    "ENTRY": "入场建议",
    "REDUCE": "减仓建议",
    "EXIT": "退出建议",
    "PENDING": "待审批",
    "APPROVED": "已批准",
    "REJECTED": "已拒绝",
    "OPEN": "持仓中",
    "CLOSED": "已结束",
    "signal_count": "信号数",
    "position_count": "持仓数",
    "structure_count": "结构事件数",
    "win_rate": "胜率",
    "avg_r": "平均 R",
    "loss_count": "亏损笔数",
    "pipeline_states": "状态更新数",
}


REASON_REPLACEMENTS: tuple[tuple[str, str], ...] = (
    ("market and stock trend passed, no structure opportunity", "市场与个股趋势通过，暂未出现结构机会"),
    ("data anomaly freezes new signals", "数据异常，冻结新入场建议"),
    ("data missing or indicators unavailable", "行情或指标缺失"),
    ("market data or indicators missing", "市场行情或指标缺失"),
    ("market indicators insufficient", "市场指标历史不足"),
    ("daily or 60m data missing", "日线或 60 分钟数据缺失"),
    ("indicator history insufficient", "指标历史不足"),
    ("pending entry signal already exists", "已有待审批入场建议"),
    ("portfolio risk checks passed", "组合风险检查通过"),
    ("risk calculation failed or stop unavailable", "风控计算失败或止损位不清晰"),
    ("generated by state machine, not score", "由状态机生成，评分未参与触发"),
    ("price recovered MA20, broke recent key high, MACD improved, volume acceptable, 60m not weak", "价格收复 MA20、接近/突破近期关键高点，MACD 改善，量能可接受，60 分钟不弱"),
    ("waiting for MA20 recovery, key high breakout, MACD improvement, volume confirmation, and 60m support", "等待收复 MA20、突破关键高点、MACD 改善、量能确认与 60 分钟支撑"),
    ("price near stage low while MACD DIF holds higher low and histogram improves", "价格接近阶段低位，DIF 未同步破低，MACD 柱改善"),
    ("price near stage high while MACD DIF fails to confirm and histogram weakens", "价格接近阶段高位，DIF 未同步创新高，MACD 柱走弱"),
    ("bottom passivation confirmed by key high breakout, MA20 recovery, MACD improvement, and acceptable volume", "底钝化后出现关键高点突破、收复 MA20、MACD 改善且量能可接受"),
    ("top passivation confirmed by key low break and continued MACD weakening", "顶钝化后跌破关键低点，MACD 继续走弱"),
    ("bottom structure failed after effective low break and renewed momentum deterioration", "底结构后有效破低，动能重新恶化"),
    ("top structure invalidated by renewed breakout with trend intact", "顶结构后重新突破，趋势仍未破坏"),
    ("hard stop triggered", "硬止损触发"),
    ("trend break exit candidate", "趋势破坏，进入退出候选"),
    ("trailing stop triggered", "滑动止盈触发"),
    ("top structure risk protection", "顶结构风险保护"),
    ("position held but latest data missing", "持仓中但最新数据缺失"),
    ("position healthy", "持仓状态正常"),
    ("manual approval created simulated position", "人工批准后创建模拟持仓"),
    ("manual approval reduced simulated position", "人工批准后模拟减仓"),
    ("simulated exit approved, cooldown started", "模拟退出已批准，进入冷却期"),
)


def label_for(value: Any) -> str:
    if value is None or value == "":
        return "-"
    key = str(value)
    return LABELS.get(key, key)


def css_class_for(value: Any) -> str:
    classes = {
        "RISK_ON": "market-risk-on",
        "NEUTRAL_POSITIVE": "market-neutral-positive",
        "NEUTRAL_NEGATIVE": "market-neutral-negative",
        "RISK_OFF": "market-risk-off",
    }
    return classes.get(str(value), "market-unknown")


def describe_market_state(value: Any) -> str:
    descriptions = {
        "RISK_ON": "市场趋势支持做多，可以寻找新机会。",
        "NEUTRAL_POSITIVE": "市场中性偏强，新仓需要降低风险。",
        "NEUTRAL_NEGATIVE": "市场偏谨慎，优先管理已有仓位。",
        "RISK_OFF": "市场风险较高，禁止生成新开仓建议。",
    }
    return descriptions.get(str(value), "市场状态尚未计算。")


def describe_script(value: Any) -> str:
    return label_for(value)


def format_reason(text: Any, limit: int | None = None) -> str:
    if text is None:
        return "-"
    result = str(text)
    for source, target in REASON_REPLACEMENTS:
        result = result.replace(source, target)
    result = re.sub(r"\bmarket state ([A-Z_]+) forbids new entries\b", lambda m: f"市场状态“{label_for(m.group(1))}”禁止新开仓", result)
    result = re.sub(r"\bstock trend ([A-Z_]+) is not eligible\b", lambda m: f"个股趋势“{label_for(m.group(1))}”不符合开仓条件", result)
    result = result.replace("UPTREND", label_for("UPTREND"))
    result = result.replace("STRONG_上涨趋势", label_for("STRONG_UPTREND"))
    result = result.replace("STRONG_UPTREND", label_for("STRONG_UPTREND"))
    result = re.sub(r"\bstop=([0-9.]+)", r"止损=\1", result)
    result = re.sub(r"\bshares=([0-9]+)", r"建议股数=\1", result)
    result = result.replace("; ", "；")
    if limit and len(result) > limit:
        return result[: max(0, limit - 1)] + "…"
    return result


def format_money(value: Any) -> str:
    try:
        return f"${float(value):,.2f}"
    except (TypeError, ValueError):
        return "-"


def format_percent(value: Any) -> str:
    try:
        return f"{float(value) * 100:.1f}%"
    except (TypeError, ValueError):
        return "-"


def format_shares(value: Any) -> str:
    try:
        return f"{int(value):,} 股"
    except (TypeError, ValueError):
        return "-"


def format_price(value: Any) -> str:
    try:
        return f"{float(value):.2f}"
    except (TypeError, ValueError):
        return "-"


def format_return(value: Any) -> str:
    try:
        number = float(value)
    except (TypeError, ValueError):
        return "-"
    return f"{number * 100:+.1f}%"


def format_datetime(value: Any) -> str:
    if isinstance(value, datetime):
        return value.strftime("%Y-%m-%d %H:%M")
    if isinstance(value, date):
        return value.strftime("%Y-%m-%d")
    return str(value) if value else "-"
